# Generated by Django 2.2 on 2021-03-27 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('display_image', models.TextField()),
                ('display_name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('email', models.TextField()),
                ('key', models.TextField()),
                ('gid', models.TextField(blank=True, null=True)),
                ('fid', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('last_active', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
    ]
