# Generated by Django 2.2 on 2021-04-17 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('required', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(unique=True)),
                ('Title', models.TextField()),
                ('Company', models.TextField()),
                ('Website', models.TextField(default='')),
                ('Location', models.TextField(default='')),
                ('Type', models.TextField(default='Permanent')),
                ('Description', models.TextField(default='')),
                ('Date_Added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
