# Generated by Django 2.2 on 2021-04-26 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Body', models.TextField()),
                ('Date_Added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
